server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update


  application:
    name: Cooking

security:
  jwt:
    key: WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw
